// This file was autogenerated by js/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../../js/globals.js', ['shapeshift.Globals.game'], [], false);
goog.addDependency('../../../../js/tutorial.js', ['shapeshift.Tutorial'], [], false);
